{% set name = "pytest-sugar" %}
{% set version = "0.9.4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b1b2186b0a72aada6859bea2a5764145e3aaa2c1cfbb23c3a19b5f7b697563d3
  patches:
    - fix_distutils_version.patch

build:
  number: 2
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - packaging >=14.1
    - pytest >=2.9
    - termcolor >=1.1.0

test:
  imports:
    - pytest_sugar
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://pivotfinland.com/pytest-sugar/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'a plugin for py.test that changes the default look and feel of py.test '
  description: |
    pytest-sugar is a plugin for py.test that shows failures and errors instantly and 
    shows a progress bar.  
  dev_url: https://github.com/Teemu/pytest-sugar/

extra:
  recipe-maintainers:
    - cshaley
    - sannykr
    - ocefpaf
